version: "3.6"
services:
    mysql:
        image: mysql:$MYSQL_VERSION
        container_name: mysql_dev
        restart: always
        ports:
            - $MYSQL_PORT:3306
        environment:
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ALLOW_EMPTY_PASSWORD=pass
            - MYSQL_DATABASE=$MYSQL_DATABASE
        volumes:
            - ./$MYSQL_DIR_DUMP:/docker-entrypoint-initdb.d/
