version: "3.6"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbimq_dev
        restart: always
        ports:
            - 5672:5672
            - 8080:15672
        environment:
            - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
            - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD
