version: "3.6"
services:
    postgresql:
        image: postgres
        container_name: postgres_dev
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        volumes:
            - ./data:/var/lib/postgresql/data
