version: "3.6"
services:
    minio:
        image: minio/minio
        container_name: minio_dev
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
            - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
        command: ["server", "/data"]
