version: "3.6"
services:
    clickhouse:
        image: yandex/clickhouse-server:$CLICKHOUSE_VERSION
        container_name: $CLICKHOUSE_CONTAINER_NAME
        restart: always
        ports:
            - $CLICKHOUSE_PORT:8123
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - ./users.xml:/etc/clickhouse-server/users.xml
            - ./clickhouse_dump:/docker-entrypoint-initdb.d/
